<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Products extends \App\Entity\Products implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'shortDescription', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'longDescription', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'buyPrice', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'sellPrice', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'availableStock', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'alertStock', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'weightGram', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'comments', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'shortDescription', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'longDescription', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'buyPrice', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'sellPrice', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'availableStock', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'alertStock', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'weightGram', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'comments', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Products $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getShortDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortDescription', []);

        return parent::getShortDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortDescription(string $shortDescription): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortDescription', [$shortDescription]);

        return parent::setShortDescription($shortDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongDescription', []);

        return parent::getLongDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongDescription(string $longDescription): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongDescription', [$longDescription]);

        return parent::setLongDescription($longDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuyPrice(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuyPrice', []);

        return parent::getBuyPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuyPrice(?string $buyPrice): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuyPrice', [$buyPrice]);

        return parent::setBuyPrice($buyPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getSellPrice(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSellPrice', []);

        return parent::getSellPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setSellPrice(string $sellPrice): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSellPrice', [$sellPrice]);

        return parent::setSellPrice($sellPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableStock(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailableStock', []);

        return parent::getAvailableStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailableStock(int $availableStock): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailableStock', [$availableStock]);

        return parent::setAvailableStock($availableStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlertStock(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlertStock', []);

        return parent::getAlertStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlertStock(int $alertStock): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlertStock', [$alertStock]);

        return parent::setAlertStock($alertStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeightGram(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeightGram', []);

        return parent::getWeightGram();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeightGram(int $weightGram): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeightGram', [$weightGram]);

        return parent::setWeightGram($weightGram);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie(): ?\App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(?\App\Entity\Categories $categorie): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function addComment(\App\Entity\Comments $comment): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComment', [$comment]);

        return parent::addComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComment(\App\Entity\Comments $comment): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComment', [$comment]);

        return parent::removeComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

}
