<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXJqRlPo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXJqRlPo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXJqRlPo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXJqRlPo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXJqRlPo\App_KernelDevDebugContainer([
    'container.build_hash' => 'XJqRlPo',
    'container.build_id' => '50677e55',
    'container.build_time' => 1631174423,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXJqRlPo');
