<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9WqGb6C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9WqGb6C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9WqGb6C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9WqGb6C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9WqGb6C\App_KernelDevDebugContainer([
    'container.build_hash' => '9WqGb6C',
    'container.build_id' => '37ec0c82',
    'container.build_time' => 1631103466,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9WqGb6C');
