<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1oDrelJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1oDrelJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1oDrelJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1oDrelJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1oDrelJ\App_KernelDevDebugContainer([
    'container.build_hash' => '1oDrelJ',
    'container.build_id' => 'f79e9349',
    'container.build_time' => 1631192492,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1oDrelJ');
